-- Миграция: добавление полей feature1-feature26 в таблицу properties
-- Выполнить если таблица уже существует

-- Добавляем feature поля (feature1-feature26) для удобств домов и вилл
ALTER TABLE properties ADD COLUMN feature1 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature2 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature3 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature4 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature5 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature6 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature7 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature8 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature9 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature10 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature11 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature12 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature13 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature14 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature15 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature16 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature17 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature18 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature19 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature20 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature21 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature22 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature23 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature24 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature25 INTEGER DEFAULT 0;
ALTER TABLE properties ADD COLUMN feature26 INTEGER DEFAULT 0;
